# Generated by Django 4.2.6 on 2023-10-30 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon')),
                ('shipping_address', models.CharField(max_length=100, verbose_name='Manzil')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
